name: Docker Image CI symphonyStarter/Apache

on:
  push:
    branches: [  symphonyStarter ]
  pull_request:
    branches: [  symphonyStarter ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
