name: symphonyStarter  CI/CD

on:
  push:
    branches:
      - symphonyStarter
  pull_request:
    branches:
      - symphonyStarter

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t back .
      - name: Tags
        run: |
          docker tag symphonyStarter ${{ secrets.DOCKER_USER }}/symphonyStarter:${{ github.sha }}
          docker tag symphonyStarter ${{ secrets.DOCKER_USER }}/symphonyStarter:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/symphonyStarter:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/symphonyStarter:latest
